Feature/movie screen bloc
EbriusQuasimodo/movies_application pull request #1
Opened 2022-08-29 08:16 UTC by EbriusQuasimodo

2022-08-29 13:18 UTC, alex-philippov requested changes

2022-08-29 13:18 UTC, alex-philippov commented on lib/bloc/movie_screen_bloc/movie_screen_bloc.dart
> +          InitialMovieScreenState(),
А что будет если ты попробуешь обновить страницу? Как я понял у тебя прогресс бар показывается при отправки InitialMovieScreenEvent с  InitialMovieScreenState'ом. Если захочешь обновить, придется снова отправлять InitialMovieScreenEvent, но это ведь уже не инициализация. InitialMovieScreenEvent надо переименовать в GetMoviesEvent, InitialMovieScreenState надо переименовать в MovieScreenState, класс стейта лучше испольховать один, сделать у него конструкторы MovieScreenState.inital(), MovieScreenState.loading(), MovieScreenState.success(), MovieScreenState.error(). Сделай по аналогии с https://github.com/felangel/bloc/blob/master/examples/flutter_dynamic_form/lib/new_car/bloc/new_car_state.dart

2022-08-29 13:18 UTC, alex-philippov commented on lib/bloc/movie_screen_bloc/movie_screen_event.dart
> +class InitialMovieScreenEvent extends MovieScreenEvent {}
GetMoviesEvent()

2022-08-29 13:18 UTC, alex-philippov commented on lib/bloc/movie_screen_bloc/movie_screen_state.dart
> +class InitialMovieScreenState extends MovieScreenState {}
Только один класс для стейта, поддерживающий разные состояния

2022-08-29 13:18 UTC, alex-philippov commented on lib/models/movie_model.dart
> +class MovieModel {
К неймингу советую сразу приучиться относиться серьезно, должна прослеживаться логика, чтобы другим разрабочиткам и тебе было проще в дальнейшем читать код. Если у тебя модель фильмов назвыется MovieModel, то модель постера должна тоже называться PosterModel, либо оставь просто Movie и Poster. Я называю такие модельки c суффиксом DTO (Data Transfer Object), например MovieDTO или PosterDTO. Подробнее о нейминге советую почитать в "Чистом Коде"

2022-08-29 13:18 UTC, alex-philippov commented on lib/models/movie_model.dart
> +      url: json['url'] ?? '',
Если какие-то поля не приходят, лучше сделать их Nullable (String? вместо String), если нет специальной какой-то логики для пустых строк, чтобы потом проще было проверять и будет одинаково для разных типов

2022-08-29 13:18 UTC, alex-philippov commented on lib/resources/api_client/api_client_dio.dart
> +    Dio dio = Dio(BaseOptions(baseUrl: 'https://api.kinopoisk.dev'));
У тебя тут Дио создается получается при каждом запросе, лучше вынести в поле класса, там сразу создать и добавить интерсептор

2022-08-29 13:18 UTC, alex-philippov commented on lib/resources/api_client/api_client_dio.dart
> +    dio.interceptors.add(
Зачем два раза добавляешь один и тот же интерсептор?)

2022-08-29 13:18 UTC, alex-philippov commented on lib/resources/movie_repository/movie_repository.dart
> +  ApiClientDio apiClient = ApiClientDio();
final

2022-08-29 13:18 UTC, alex-philippov commented on lib/resources/movie_repository/movie_repository.dart
> +  ApiClientDio apiClient = ApiClientDio();
Все по возможности делай файнал, так меньше вероятность что допущения ошибки

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +            InitialMovieScreenEvent(),
вот тут получается будет GetMoviesEvent(). Кстати, если речь идет об вызове функции в какой либо библиотеке, которая принимает только 1 аргумент, то добавление trailing comma необязтельно. Все равно туда уже новые аргументы добавятся только в случает изменения апи либы, короче тут на свое усмотрение, можешь ставить, а можешь нет

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +  Widget _movieBloc(context) {
Всегда добавляй тип для параметров  функций: Widget _movieBloc(BuildContext context)

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +        print(state.runtimeType);
Когда заливаем код в мастер, то дебажные логи надо убирать, для чистоты кода

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +          return Padding(
Такой паддинг не подойдет) попробуй немного проскроллить и увидишь как картинка немного обрезается, появляется белое пространство после АппБара. Попробуй вместо этого использовать параметр padding у GridView

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +  Widget _movieItems(BuildContext context, MovieModel element) {
Снова про нейминг. По своему смыслу, если не смотреть код функции, мне сразу кажется, что тут возвращается, какой-нибудь лист или грид с итемами, хотя функция билдит только 1 итем. Чтобы понять как назвать, надо задать себе вопрос, что делает функция? Функция билдит один муви итем, знач лучше назвать как-нибудь _buildMovieItem

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +    return Container(
Я думаю тут сама видишь, что верстка выглядит неоч: супер большой какой-то паддинг получился снизу итема, InkWell тоже странно тут выглядит, по сути он тут не нужен, так как у тебя сразу откроется другой экран и анимация ripple не успеет отработать, оставь тут вместо него GestureDetector пока  попробуй переверстать чтобы норм выглядело, если не будет получаться, звони, сделаем вместе

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +    return Container(
Советую сразу представить в голове какие элементы верстки какое место должны занимать и какая должна быть логика расположения и потом стараться это реализовать

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +                    element.name!,
А если name будет null?

2022-08-29 13:18 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +                    element.year!.toString(),
Если null придет?

2022-08-30 07:00 UTC, EbriusQuasimodo commented on lib/resources/api_client/api_client_dio.dart
> +    Dio dio = Dio(BaseOptions(baseUrl: 'https://api.kinopoisk.dev'));
может я что-то не так делаю, но интерсептор не получается добавить

2022-08-30 09:14 UTC, EbriusQuasimodo commented on lib/screens/home/movie_screen.dart
> +                    element.name!,
сделала, но он выводит предупреждение в консоль:
Warning: Operand of null-aware operation '??' has type 'String' which excludes null.
                    element.name! ?? '',

2022-08-30 09:39 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +                    element.name!,
После name! убери !, когда ставишь в конец !, то возвращаемое значение от выражения "element.name!" уже не может быть null

2022-09-01 07:29 UTC, alex-philippov commented on lib/resources/api_client/api_client_dio.dart
> +    Dio dio = Dio(BaseOptions(baseUrl: 'https://api.kinopoisk.dev'));
```
final Dio dio = Dio(BaseOptions(baseUrl: 'https://api.kinopoisk.dev'))..interceptors.add(...);
```  
Так пробовала?

2022-09-01 07:29 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +                    element.name!,
Другими словами, тип возвращаемого значения от element.name - String?, а от element.name! - String. Ты пытаешься использовать оператор ??, который можно использовать только с Nullable типами, в данном случае String? -  Nullable, а String - не Nullable

2022-09-01 07:29 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +                element.year.toString() ?? '',
Забыла ? после year: element.year?.toString() ?? '',

2022-09-01 07:29 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +        if (state == const MovieScreenState.error()) {
Надо добавить в стейт либо булевы поля для проверки статуса загрузки либо енум поле со статусом, можешь посмотреть вот тут как сделано: https://github.com/felangel/bloc/blob/master/examples/flutter_complex_list/lib/complex_list/cubit/complex_list_state.dart

2022-09-01 07:29 UTC, alex-philippov commented on lib/screens/home/movie_screen.dart
> +    return Column(
Смотри, аспект ты задешь при создании грида, получается размер родителя итема будет фиксированный, тебе нужно в него положить колонну, которая будет занимать максимум места - mainAxisSize: MainAxisSize.max, все, у тебя получается колонна во всю высоту итема, далее тебе нужно положить вниз текст, а сверху растянуть изображение на оставшуюся площадь. Для этого оберни изображение в Expanded и задай изабражение fit: BoxFit.cover - это поместит растянет и обрежет картинку по центру, SizedBox там не нужен. А текст оставь без Expanded и лишнюю колонну тоже можно убрать

2022-09-01 08:30 UTC, alex-philippov approved these changes
Супер

2022-09-01 08:31 UTC, merged